/**
 * Labrinth
 *
 * This API is documented in the **OpenAPI format** and is available for download [here](/openapi.yaml).  There are some undocumented routes. These routes are not meant for public use, such as the routes for adding new items to tags.  ## Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with the [W3C spec](https://www.w3.org/TR/cors/). This allows for cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  ## Authentication This API uses GitHub tokens for authentication. The token is in the `Authorization` header of the request. You can get a token [here](#operation/initAuth).    Example:  ```  Authorization: gho_pJ9dGXVKpfzZp4PUHSxYEq9hjk0h288Gwj4S  ```  ## Ratelimits The API has a ratelimit defined per IP. Limits and remaining amounts are given in the response headers. The `X-Ratelimit-Limit` header is the maximum number of requests that can be made in a minute. The `X-Ratelimit-Remaining` header is the number of requests remaining in the current ratelimit window. The `X-Ratelimit-Reset` header is the time in seconds until the ratelimit window resets. 
 *
 * The version of the OpenAPI document: f3234a6 (v2)
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.axay.pacmc.repoapi.modrinth.model

import net.axay.pacmc.repoapi.modrinth.model.BaseVersionDependencies

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name The name of this version
 * @param versionNumber The version number. Ideally will follow semantic versioning
 * @param gameVersions A list of versions of Minecraft that this version supports
 * @param versionType The release channel for this version
 * @param loaders The mod loaders that this version supports
 * @param featured Whether the version is featured or not
 * @param changelog The changelog for this version
 * @param changelogUrl A link to the changelog for this version
 * @param dependencies A list of specific versions of projects that this version depends on
 */
@Serializable
data class BaseVersion (

    /* The name of this version */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The version number. Ideally will follow semantic versioning */
    @SerialName(value = "version_number") @Required val versionNumber: kotlin.String,

    /* A list of versions of Minecraft that this version supports */
    @SerialName(value = "game_versions") @Required val gameVersions: kotlin.collections.List<kotlin.String>,

    /* The release channel for this version */
    @SerialName(value = "version_type") @Required val versionType: BaseVersion.VersionType,

    /* The mod loaders that this version supports */
    @SerialName(value = "loaders") @Required val loaders: kotlin.collections.List<kotlin.String>,

    /* Whether the version is featured or not */
    @SerialName(value = "featured") @Required val featured: kotlin.Boolean,

    /* The changelog for this version */
    @SerialName(value = "changelog") val changelog: kotlin.String? = null,

    /* A link to the changelog for this version */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "changelog_url") val changelogUrl: kotlin.String? = null,

    /* A list of specific versions of projects that this version depends on */
    @SerialName(value = "dependencies") val dependencies: kotlin.collections.List<BaseVersionDependencies>? = null

) {

    /**
     * The release channel for this version
     *
     * Values: release,beta,alpha
     */
    @Serializable
    enum class VersionType(val value: kotlin.String) {
        @SerialName(value = "release") release("release"),
        @SerialName(value = "beta") beta("beta"),
        @SerialName(value = "alpha") alpha("alpha");
    }
}

