/**
 * Labrinth
 *
 * This API is documented in the **OpenAPI format** and is available for download [here](/openapi.yaml).  # Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/). This allows for cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  # Authentication This API uses GitHub tokens for authentication. The token is in the `Authorization` header of the request. You can get a token [here](#operation/initAuth).   Example:  ```  Authorization: gho_pJ9dGXVKpfzZp4PUHSxYEq9hjk0h288Gwj4S  ``` 
 *
 * The version of the OpenAPI document: 13187de (v2)
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.axay.pacmc.repoapi.modrinth.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The ID of the donation platform
 * @param platform The donation platform this link is to
 * @param url The URL of the donation platform and user
 */
@Serializable
data class EditableProjectAllOfDonationUrls (

    /* The ID of the donation platform */
    @SerialName(value = "id") val id: EditableProjectAllOfDonationUrls.Id? = null,

    /* The donation platform this link is to */
    @SerialName(value = "platform") val platform: EditableProjectAllOfDonationUrls.Platform? = null,

    /* The URL of the donation platform and user */
    @SerialName(value = "url") val url: kotlin.String? = null

) {

    /**
     * The ID of the donation platform
     *
     * Values: patreon,bmac,paypal,github,koMinusFi,other
     */
    @Serializable
    enum class Id(val value: kotlin.String) {
        @SerialName(value = "patreon") patreon("patreon"),
        @SerialName(value = "bmac") bmac("bmac"),
        @SerialName(value = "paypal") paypal("paypal"),
        @SerialName(value = "github") github("github"),
        @SerialName(value = "ko-fi") koMinusFi("ko-fi"),
        @SerialName(value = "other") other("other");
    }
    /**
     * The donation platform this link is to
     *
     * Values: patreon,byMeACoffee,payPal,gitHubSponsors,koMinusFi,other
     */
    @Serializable
    enum class Platform(val value: kotlin.String) {
        @SerialName(value = "Patreon") patreon("Patreon"),
        @SerialName(value = "By Me a Coffee") byMeACoffee("By Me a Coffee"),
        @SerialName(value = "PayPal") payPal("PayPal"),
        @SerialName(value = "GitHub Sponsors") gitHubSponsors("GitHub Sponsors"),
        @SerialName(value = "Ko-Fi") koMinusFi("Ko-Fi"),
        @SerialName(value = "Other") other("Other");
    }
}

