/**
 * Labrinth
 *
 * This API is documented in the **OpenAPI format** and is available for download [here](/openapi.yaml).  # Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/). This allows for cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  # Authentication This API uses GitHub tokens for authentication. The token is in the `Authorization` header of the request. You can get a token [here](#operation/initAuth).   Example:  ```  Authorization: gho_pJ9dGXVKpfzZp4PUHSxYEq9hjk0h288Gwj4S  ``` 
 *
 * The version of the OpenAPI document: 13187de (v2)
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.axay.pacmc.repoapi.modrinth.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The id of the notification
 * @param userId The id of the user who received the notification
 * @param title The title of the notification
 * @param text The body text of the notification
 * @param link A link to the related project or version
 * @param read Whether the notification has been read or not
 * @param created The time at which the notification was created
 * @param actions A list of actions that can be performed
 * @param type The type of notification
 */
@Serializable
data class Notification (

    /* The id of the notification */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The id of the user who received the notification */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* The title of the notification */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* The body text of the notification */
    @SerialName(value = "text") @Required val text: kotlin.String,

    /* A link to the related project or version */
    @SerialName(value = "link") @Required val link: kotlin.String,

    /* Whether the notification has been read or not */
    @SerialName(value = "read") @Required val read: kotlin.Boolean,

    /* The time at which the notification was created */
    @SerialName(value = "created") @Required val created: kotlin.String,

    /* A list of actions that can be performed */
    @SerialName(value = "actions") @Required val actions: kotlin.collections.List<kotlin.String>,

    /* The type of notification */
    @SerialName(value = "type") val type: kotlin.String? = null

)

