/**
 * Labrinth
 *
 * This API is documented in the **OpenAPI format** and is available for download [here](/openapi.yaml).  # Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/). This allows for cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  # Authentication This API uses GitHub tokens for authentication. The token is in the `Authorization` header of the request. You can get a token [here](#operation/initAuth).    Example:  ```  Authorization: gho_pJ9dGXVKpfzZp4PUHSxYEq9hjk0h288Gwj4S  ``` 
 *
 * The version of the OpenAPI document: 13187de (v2)
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.axay.pacmc.repoapi.modrinth.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param teamId The team's ID
 * @param userId The user's ID
 * @param role The user's role on the team
 * @param permissions The user's permissions in bitflag format (requires authorization)
 * @param accepted Whether or not the user has accepted to be on the team (requires authorization)
 */
@Serializable
data class Team (

    /* The team's ID */
    @SerialName(value = "team_id") val teamId: kotlin.String? = null,

    /* The user's ID */
    @SerialName(value = "user_id") val userId: kotlin.String? = null,

    /* The user's role on the team */
    @SerialName(value = "role") val role: kotlin.String? = null,

    /* The user's permissions in bitflag format (requires authorization) */
    @SerialName(value = "permissions") val permissions: kotlin.Int? = null,

    /* Whether or not the user has accepted to be on the team (requires authorization) */
    @SerialName(value = "accepted") val accepted: kotlin.Boolean? = null

)

