/**
 * Labrinth
 *
 * This API is documented in the **OpenAPI format** and is available for download [here](/openapi.yaml).  # Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/). This allows for cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  # Authentication This API uses GitHub tokens for authentication. The token is in the `Authorization` header of the request. You can get a token [here](#operation/initAuth).   Example:  ```  Authorization: gho_pJ9dGXVKpfzZp4PUHSxYEq9hjk0h288Gwj4S  ``` 
 *
 * The version of the OpenAPI document: 13187de (v2)
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.axay.pacmc.repoapi.modrinth.model

import net.axay.pacmc.repoapi.modrinth.model.User

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param teamId The ID of the team this team member is a member of
 * @param user 
 * @param role The user's role on the team
 * @param accepted Whether or not the user has accepted to be on the team (requires authorization)
 * @param permissions The user's permissions in bitflag format (requires authorization)
 */
@Serializable
data class TeamMember (

    /* The ID of the team this team member is a member of */
    @SerialName(value = "team_id") @Required val teamId: kotlin.String,

    @SerialName(value = "user") @Required val user: User,

    /* The user's role on the team */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* Whether or not the user has accepted to be on the team (requires authorization) */
    @SerialName(value = "accepted") @Required val accepted: kotlin.Boolean,

    /* The user's permissions in bitflag format (requires authorization) */
    @SerialName(value = "permissions") val permissions: kotlin.Int? = null

)

