/**
 * Labrinth
 *
 * This API is documented in the **OpenAPI format** and is available for download [here](/openapi.yaml).  There are some undocumented routes. These routes are not meant for public use, such as the routes for adding new items to tags.  ## Cross-Origin Resource Sharing This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with the [W3C spec](https://www.w3.org/TR/cors/). This allows for cross-domain communication from the browser. All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.  ## Authentication This API uses GitHub tokens for authentication. The token is in the `Authorization` header of the request. You can get a token [here](#operation/initAuth).    Example:  ```  Authorization: gho_pJ9dGXVKpfzZp4PUHSxYEq9hjk0h288Gwj4S  ```  ## Ratelimits The API has a ratelimit defined per IP. Limits and remaining amounts are given in the response headers. The `X-Ratelimit-Limit` header is the maximum number of requests that can be made in a minute. The `X-Ratelimit-Remaining` header is the number of requests remaining in the current ratelimit window. The `X-Ratelimit-Reset` header is the time in seconds until the ratelimit window resets. 
 *
 * The version of the OpenAPI document: f3234a6 (v2)
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.axay.pacmc.repoapi.modrinth.model

import net.axay.pacmc.repoapi.modrinth.model.VersionAllOfFiles

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id The ID of the version, encoded as a base62 string
 * @param projectId The ID of the project this version is for
 * @param authorId The ID of the author who published this version
 * @param datePublished 
 * @param downloads The number of times this version has been downloaded
 * @param files A list of files available for download for this version
 */
@Serializable
data class VersionAllOf (

    /* The ID of the version, encoded as a base62 string */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The ID of the project this version is for */
    @SerialName(value = "project_id") @Required val projectId: kotlin.String,

    /* The ID of the author who published this version */
    @SerialName(value = "author_id") @Required val authorId: kotlin.String,

    @SerialName(value = "date_published") @Required val datePublished: kotlin.String,

    /* The number of times this version has been downloaded */
    @SerialName(value = "downloads") @Required val downloads: kotlin.Int,

    /* A list of files available for download for this version */
    @SerialName(value = "files") @Required val files: kotlin.collections.List<VersionAllOfFiles>

)

